package testFramework.enums;

import java.io.Serializable;

/**
 *
 * @author Garth Bosch
 */
public enum PageElements implements Serializable {

    /**
     * *** For all pages ****
     */
    SaveButton("SaveButton", "Save"),
    Save("Save", "Save"),
    SubmitButton("submit", "Submit"),
    SubmitButtonName("btnSubmit", "Submit"),
    FloatingMessageBox("messages", "Messages"),
    FloatingMessageBoxCloseButton("ui-button-text", "Close"),
    FloatingMessageBoxConfirmButton("ui-button-text", "Confirm"),
    FloatingMessageBoxAddButton("ui-button-text", "Confirm"),
    FloatingMessageUibuttonSet("ui-dialog-buttonset", "UI button set"),
    LeftPane("leftnav", "leftnav"),
    SomeElement("someElement", "No Specific element"),
    /**
     * *** Schemes Page ****
     */
    //    SchemesNavigateToLink("Schemes"),
    SchemesNavigateToLink("//a[contains(@href, '/Scheme')]", "Schemes"),
//    SchemesNavigateToLink("Schemes", "Schemes"),
    SchemesCreateBSSPLink("Create BSSP", "Create BSSP"),
    SchemesMinRequirementId("minReq", "Min Requirement New"),
    SchemesMinRequirementIdUpdate("schemereqWrapper", "Min Requirement Update"),
    SchemesMinRequirementLinkId("MinimumRequirements", "Minimum Requirements"),
    SchemesMinReqsYesOption("cb-enable", "Min Reqs Yes"),
    SchemesMinReqsNoOption("cb-disable selected", "Min Reqs No"),
//    SchemesMinReqsVendorNameDropDown("_usedBy", "Min Reqs Vendor Name"),    
    SchemesMinReqsVendorNameDropDown("MinRequirements_6__Value", "Min Reqs Vendor Name"),    
    SchemesMinReqsVendorNameUpdateBSSPDropDown("Requirements_4__Value", "BSSP Update Min Reqs Vendor Name"),    
    SchemesMinReqsVendorNameUpdateGFSDropDown("Requirements_6__Value", "GFS Update Min Reqs Vendor Name"),    
    SchemesMinReqsDateId("MinRequirements_15__Value", "Min Reqs Date"),
    SchemesMinReqsDateIdUpdate("Requirements_15__Value", "Min Reqs Date"),
    SchemesNextButton("btnNext", "Next"),
    SchemesDetailsLink("Schemes Details", "Schemes Details"),
    SchemesSchemeNameTextField("Scheme_SchemeName", "Scheme Name"),
    SchemesSchemeTypeDropDown("Scheme_SchemeTypeID", "Scheme Type"),
    SchemesSchemeRegionIDDropDown("Scheme_RegionID", "Region"),
    SchemesSchemeContactTitleDropDown("SchemeContact_Title", "Title"),
    SchemesSchemeContactSurnameTextBox("SchemeContact_Surname", "Surname"),
    SchemesSchemeContactFirstnameTextBox("SchemeContact_Firstname", "Firstname"),
    SchemesSchemeContactEmailTextBox("SchemeContact_Email", "Scheme Contact Email"),
    SchemesContactPhoneNoTextBox("cpTel", "Contact Phone No"),
    SchemesContactPhoneFaxNoTextBox("cpFax", "Contact Phone Fax No"),
    SchemesContactPhoneCellNoTextBox("cpCell", "Contact Phone Cell No"),
    SchemesStreetAddress1TextBox("sLine1", "Street Address 1"),
    SchemesStreetAddress2TextBox("sLine2", "Street Address 2"),
    SchemesStreetAddress3TextBox("sLine3", "Street Address 3"),
    SchemesStreetAddress4TextBox("sLine4", "Street Address 4"),
    SchemesStreetAddressPostalCodeTextBox("sPostalCode", "Street Address Postal Code"),
    SchemesStreetAddressCityTextBox("sLine5", "Street Address City"),
    SchemesStreetAddressCountryDropDown("sCountry", "Street Address Country"),
    SchemesStreetAddressSameForPostalCheckBox("spa", "Same For Postal"),
    SchemesPostalAddress1TextBox("pLine1", "Postal Address 1"),
    SchemesPostalAddress2TextBox("pLine2", "Postal Address 2"),
    SchemesPostalAddress3TextBox("pLine3", "Postal Address 3"),
    SchemesPostalAddress4TextBox("pLine4", "Postal Address 4"),
    SchemesPostalAddressPostalCodeTextBox("pPostalCode", "Postal Address Postal Code"),
    SchemesPostalAddressCityTextBox("pLine5", "Postal Address City"),
    SchemesBankingDetailsBankNameDropDown("BankDetail_BankNameID", "Bank Name"),
    SchemesBankingDetailsBankCodeTextBox("BankDetail_BankSortCode", "Bank Code"),
    SchemesBankingAccNoTextBox("BankDetail_BankAccNo", "Bank Acc Number"),
    SchemesBankingAccTypeDropDown("BankDetail_BankAccTypeID", "Bank Acc Type"),
    SchemesPaymentMethodTypeDropDown("PaymentMethod_PaymentMethod_PaymentMethodDescription", "Payment Method"),
    SchemesPaymentMethodPaymentDayDropDown("PaymentMethod_PaymentDay_Day", "Payment Day"),
    SchemesPaymentMethodTypeUpdateDropDown("Scheme_PremiumPayment_PaymentMethod_PaymentMethodDescription", "Payment Method"),
    SchemesPaymentMethodPaymentDayUpdateDropDown("Scheme_PremiumPayment_PaymentDay_Day", "Payment Day"),
    SchemesServicingConsultantStaffCodeTextBox("SchemeServicingConsultant_OperationCode", "Operation Code"),
    SchemesSalesConsultantStaffCodeTextBox("SchemeSalesConsultant_OperationCode", "Staff Code"),
    SchemesSalesConsultantStaffCodeUpdateTextBox("SalesConsultant_OperationCode", "Staff Code"),
    SchemesAddSchemeButton("//input[@type='submit' and @value='Add Scheme']", "Add Scheme"),
    SchemesAddSchemeProductOptionButton("//input[@type='submit' and @value='Add']", "Add Option"),
    SchemeInformationLeftNavLabel("leftnav", "leftnav"),
    SchemeHeadingLabel("contentheader", "Scheme Heading"),
    SchemeSaveButton("//input[@type='submit' and @value='Save']", "Scheme Save"),
    SchemeMinReqUpdateSaveButton("//div[@id='ui-tabs-3']//div[@id='schemereqWrapper']//form//fieldset//table//tbody//tr//td//input[@type='submit' and @value='Save']", "Min Req Update Save"),
    SchemesSchemeUpdateLink("Scheme Update", "Scheme Update"),
    SchemesCashBackIndicatorViaUpdateCheckBox("Scheme_CashbackIndicator", "Cash back Indicator"),    
//     Policy Admin
    SchemesPolicyAdminProductTableID("tblsummary", "Product Summary Table"),
    SchemesAddOptionButton("btnNewOption", "AddOption"),
    SchemesPolicyAdminButton("PolicyAdmin", "Policy Admin"),
    SchemesAddProductDropdownBox("ddlProducts", "Add Product"),
    SchemesAddCoverDropdownBox("ddlCovers", "Add Cover"),
    SchemesPolicyAdminProductDescLabel("bsspPolicyAdminWrapper", "Policy Admin Product"),
    SchemesPolicyAdminLink("Policy Admin", "Policy Admin"),
    SchemesTransactionHistoryLink("Transaction History", "Transaction History"),
    SetSchemeToBeAssessedButton("btnTba", "To Be Assessed"),
    SchemeAddMemberButton("addMember", "Add Member"),
    SchemesCashConfirmationButton("ConfirmPayment", "Confirm Payment"),
    SchemesProductTableId("//div[@id='ui-tabs-4']//div[@id='schemepolicyAdminWrapper']//table[@id='tblsummary']//tbody", "Policy Admin Product Table"),    
    SchemesBackToPolicyAdminButton("//div[@id='main']//table//tbody//tr//td[@class='contentRight']//span[@class='ui-button-text']", "Back To Policy Admin"),
    SchemesDownloadAgeProfileLink("Download Age Profile", "Download Age Profile"),
    SchemesInfoTable("schemeInfoWrapper", "Scheme Information Table"),
    
    //    Searching
    SchemesSearchNameTextBox("SchemeName", "Scheme Name"),
    SchemeSearchButton("//input[@type='submit' and @value='Search']", "Search"),
//    SchemeUpdateButton("//img[@alt='Update Scheme' and @title='Update Scheme']", "Update Scheme"),
    SchemeUpdateButton("//img[contains(@src, '/Content/Images/ico_editItem.png')]", "Update Scheme"),
    SchemeViewButton("//img[contains(@src, '/Content/Images/ico_viewItem.png')]", "View Scheme"),
    SchemeUpdateButtonSidePane("Update Scheme", "Update Scheme"),
    //    Members
    SchemesAddingPrincipleMemberButton("//img[contains(@src, '/Content/Images/ico_users_plus.png')]", "Add Principle Member"),
    SchemesAddingMemberLink("//img[contains(@src, '/Content/Images/ico_users_plus.png')]", "Adding Member"),
    PrincipalMembersIdNumberTextBox("IdNumber", "Main Member Id Number"),
    PrincipalMembersTitleDropDownBox("Title", "Main Member Title"),
    PrincipalMembersSurnameTextBox("Surname", "Main Member Surname"),
    PrincipalMembersFirstnameTextBox("Firstname", "Main Member Firstname"),
    PrincipalMembersGenderDropDownBox("Gender", "Main Member Gender"),
    PrincipalMembersDateOfBirthTextBox("DateOfBirth", "Main Memeber Date Of Birth"),
    PrincipalMembersWaitingPeriodDropDownBox("WaitingPeriod", "Main Memeber WaitingPeriod"),
    PrincipalMembersJoinDateTextBox("JoinDate", "Main Memeber JoinDate"),
    PrincipalMemberCoverDropDownBox("Cover", "Main Member Cover"),
    PolicyMemberCoverDropDownBox("PolicyMember_CoverAmount", "Member Cover"),
    PrincipalMembersNextActionsDropDownBox("NextActions", "Main Memeber Next Actions"),
    PolicyMembersIdNumberTextBox("PolicyMember_IdNumber", "Id Number"),
    PolicyMembersTitleDropDownBox("PolicyMember_Title", "Title"),
    PolicyMembersSurnameTextBox("PolicyMember_Surname", "Surname"),
    PolicyMembersFirstnameTextBox("PolicyMember_Firstname", "Firstname"),
    PolicyMembersGenderDropDownBox("PolicyMember_Gender", "Gender"),
    PolicyMembersDateOfBirthTextBox("PolicyMember_DateOfBirth", "Date Of Birth"),
    PolicyMembersWaitingPeriodDropDownBox("PolicyMember_WaitingPeriod", "Waiting Period"),
    PolicyMembersJoinDateTextBox("PolicyMember_JoinDate", "Join Date"),
    PolicyMembersNextActionsDropDownBox("PolicyMember_NextActions", "Next Actions"),
    PolicyMembersExceptionDropDownBox("PolicyMember_Exception", "Exception"),    
    //    Assess
    SchemeAssessmentAcceptRadioButton("rAccept", "Accept"),
    SchemeAssessButton("//input[@type='submit' and @value='Assess']", "Assess"),
    SchemeAssessMinWaitPeriodSelectionBox("MinimumWaitingPeriod", "Min Wait Period"),
    SchemeAssessMaxWaitPeriodSelectionBox("MaximimWaitingPeriod", "Max Wait Period"),
    SchemeAssessCoreFamilyOptionRiskDropDown("AssessSchemeOptions_CoreFamilyOptions_0__RiskId", "Core Family Options 0 Risk"),
    SchemeAssessCoreFamilyOptionPMWaitingPeriodDropDown("AssessSchemeOptions_CoreFamilyOptions_0__PmWaitingPeriod", "Core Family Options 0 PM Waiting Period"),
    SchemeAssessCoreFamilyOptionADWaitingPeriodDropDown("AssessSchemeOptions_CoreFamilyOptions_0__AdWaitingPeriod", "Core Family Options 0 AD Waiting Period"),
    //    Cash Confirmation
    SchemesCashPaymentLabel("cashPayments", "Cash Payment"),
    SchemesConfirmPaymentForRadioButton1("ForDate1", "Payment For 1"),
    SchemesConfirmPaymentForRadioButton2("ForDate2", "Payment For 2"),
    SchemesConfirmPaymentPremiumReceivedTextBox("PaymentReceived", "Payment Received"),
    SchemesConfirmPaymentPremiumReceivedTextBoxLapsedScheme("CashPayment_PremiumReceived", "Payment Received"),
    SchemesConfirmPaymentDateReceivedTextBox("DateReceived", "Date Received"),
    SchemesConfirmPaymentDateReceivedTextBoxLapsedScheme("CashPayment_DateReceived", "Date Received"),
    SchemesConfirmPaymentNoOfPremiumsDropdownLapsedScheme("CashPayment_NumPremiums", "No. of premiums"),
    SchemesConfirmPaymentPaymentTypeDropdownLapsedScheme("CashPayment_M65Type", "Payment Type"),
    SchemesTransactionHistoryTable("schemeTxHistoryWrapper", "Transaction History Table"),
    SchemesConfirmPaymentPMARActionDateDropDown("Pmar_ActionDate", "PMAR Deduction Date"),
    
    // Minimum Requirements
    SchemeMinReqDiv("ui-tabs-3", "Min Req Tab"),
    /*
     * *** Quotes Page ****
     */
    QuotesNavigateToLink("//a[contains(@href, '/Quote')]", "Quotes"),
    QuotesCreateQuoteLink("Create Quote", "Create Quote"),
    QuotesCreateGFSQuoteNormalLink("//img[contains(@src, '/Content/Images/gfsNormal.png')]", "Create GFS Quote Normal"),
    QuotesCreateGFSQuoteCustomisedLink("//img[contains(@src, '/Content/Images/gfsCustomised.png')]", "Create GFS Quote Customised"),
    QuotesCreateBSSPCustomisedQuoteLink("//img[contains(@src, '/Content/Images/bsspCustomised.png')]", "Create BSSP Customised"),
    QuotesMinReqsVatNoTextbox("Requirements_3__Value", "Min Reqs Vat No"),
    QuotesGFSMinReqsDateReceivedTextbox("Requirements_7__Value", "Min Reqs Date Received"),
    QuotesBSSPMinReqsDateReceivedTextbox("Requirements_5__Value", "Min Reqs Date Received"),
    QuotesNextButton("//input[@type='submit' and @value='Next >>']", "Next"),
    QuoteGFSMinReqsVendorNameDropDown("Requirements_5__Value", "Quote GFS Min Reqs Vendor Name"),
    QuoteBSSPMinReqsVendorNameDropDown("Requirements_3__Value", "Quote BSSP Min Reqs Vendor Name"),
    QuotesSchemeNameTextField("QuoteInformation_Scheme_SchemeName", "Scheme Name"),
    QuotesSchemeTypeDropDown("QuoteInformation_Scheme_SchemeType", "Scheme Type"),
    QuotesSchemeLicenseNoTextbox("QuoteInformation_Scheme_FspLicenseNumber", "Scheme License No"),
    QuotesSchemeRegionIDDropDown("QuoteInformation_Scheme_SchemeRegion", "Scheme Region"),
    QuotesSchemeContactTitleDropDown("QuoteInformation_Contact_Title", "Scheme Contact Title"),
    QuotesSchemeContactSurnameTextBox("QuoteInformation_Contact_Surname", "Scheme Contact Surname"),
    QuotesSchemeContactFirstnameTextBox("QuoteInformation_Contact_Firstname", "Scheme Contact Firstname"),
    QuotesSchemeContactEmailTextBox("QuoteInformation_Contact_Email", "Scheme Contact Email"),
    QuotesContactPhoneNoTextBox("cpTel", "Contact Phone No"),
    QuotesContactPhoneFaxNoTextBox("cpFax", "Contact Phone Fax No"),
    QuotesContactPhoneCellNoTextBox("cpCell", "Contact Phone Cell No"),
    QuotesStreetAddress1TextBox("sLine1", "Street Address 1"),
    QuotesStreetAddress2TextBox("sLine2", "Street Address 2"),
    QuotesStreetAddress3TextBox("sLine3", "Street Address 3"),
    QuotesStreetAddress4TextBox("sLine4", "Street Address 4"),
    QuotesStreetAddressPostalCodeTextBox("sPostalCode", "Street Address Postal Code"),
    QuotesStreetAddressCityTextBox("sLine5", "Street Address City"),
    QuotesStreetAddressCountryDropDown("sCountry", "Street Address Country"),
    QuotesStreetAddressSameForPostalCheckBox("spa", "Same For Postal"),
    QuotesPostalAddress1TextBox("pLine1", "Postal Address 1"),
    QuotesPostalAddress2TextBox("pLine2", "Postal Address 2"),
    QuotesPostalAddress3TextBox("pLine3", "Postal Address 3"),
    QuotesPostalAddress4TextBox("pLine4", "Postal Address 4"),
    QuotesPostalAddressPostalCodeTextBox("pPostalCode", "Postal Address Postal Code"),
    QuotesPostalAddressCityTextBox("pLine5", "Postal Address City"),
    QuotesServicingConsultantStaffCodeTextBox("QuoteInformation_ServicingConsultant_OperationCode", "Servicing Consultant Staff Code"),
    QuotesAddQuoteButton("//input[@type='submit' and @value='Add Quote']", "Add Quote"),
    QuotesContinueButton("Continue", "Continue"),
    SearchingActionsSection("//td[@class='tableActionIcon']", "Actions"),
    QuotesViewDetailsButton("//img[@alt='View Scheme Details' and @title='View Scheme Details']", "View Details"),
//    QuotesViewDetailsButton("//img[contains(@src, '/Content/Images/ico_viewItem.png')]", "View Details"),
    QuotesProducAnalysisAgeBand15000Male0To15Textbox("ProductAnalysis_AgeProfile_AgeBandRows_0__MaleAgeBands_0__Value", "ProducAnalysisAgeBand15000Male0To15"),
    QuotesProducAnalysisAgeBand15000Female0To15Textbox("ProductAnalysis_AgeProfile_AgeBandRows_0__FemaleAgeBands_0__Value", "ProducAnalysisAgeBand15000Female0To15"),
    QuotesProducAnalysisAgeBand15000Male16To64Textbox("ProductAnalysis_AgeProfile_AgeBandRows_0__MaleAgeBands_1__Value", "ProducAnalysisAgeBand15000Male16To64"),
    QuotesProducAnalysisAgeBand15000Female16To64Textbox("ProductAnalysis_AgeProfile_AgeBandRows_0__FemaleAgeBands_1__Value", "ProducAnalysisAgeBand15000Female16To64"),    
    QuotesProducAnalysisAgeBand15000Male65To74Textbox("ProductAnalysis_AgeProfile_AgeBandRows_0__MaleAgeBands_2__Value", "ProducAnalysisAgeBand15000Male65To74"),
    QuotesProducAnalysisAgeBand15000Female65To74Textbox("ProductAnalysis_AgeProfile_AgeBandRows_0__FemaleAgeBands_2__Value", "ProducAnalysisAgeBand15000Female65To74"),
    QuotesProducAnalysisAgeBand15000Male75To84Textbox("ProductAnalysis_AgeProfile_AgeBandRows_0__MaleAgeBands_3__Value", "ProducAnalysisAgeBand15000Male75To84"),
    QuotesProducAnalysisAgeBand15000Female75To84Textbox("ProductAnalysis_AgeProfile_AgeBandRows_0__FemaleAgeBands_3__Value", "ProducAnalysisAgeBand15000Female75To84"),
    QuotesProducAnalysisAgeBand15000Male85To100Textbox("ProductAnalysis_AgeProfile_AgeBandRows_0__MaleAgeBands_4__Value", "ProducAnalysisAgeBand15000Male85To100"),
    QuotesProducAnalysisAgeBand15000Female85To100Textbox("ProductAnalysis_AgeProfile_AgeBandRows_0__FemaleAgeBands_4__Value", "ProducAnalysisAgeBand15000Female85To100"),    
    QuotesBSSPProducAnalysisAgeBand15000Male0To15Textbox("ProductAnalysis_AgeProfile_BsspAgeBandRows_0__Agebands_0__MaleCount", "BSSPProducAnalysisAgeBand15000Male0To15"),
    QuotesBSSPProducAnalysisAgeBand15000Female0To15Textbox("ProductAnalysis_AgeProfile_BsspAgeBandRows_0__Agebands_0__FemaleCount", "BSSPProducAnalysisAgeBand15000Female0To15"),
    QuotesBSSPProducAnalysisAgeBand15000Male16To64Textbox("ProductAnalysis_AgeProfile_BsspAgeBandRows_0__Agebands_1__MaleCount", "BSSPProducAnalysisAgeBand15000Male16To64"),
    QuotesBSSPProducAnalysisAgeBand15000Female16To64Textbox("ProductAnalysis_AgeProfile_BsspAgeBandRows_0__Agebands_1__FemaleCount", "BSSPProducAnalysisAgeBand15000Female16To64"),    
    QuotesBSSPProducAnalysisAgeBand15000Male65To74Textbox("ProductAnalysis_AgeProfile_BsspAgeBandRows_0__Agebands_2__MaleCount", "BSSPProducAnalysisAgeBand15000Male65To74"),
    QuotesBSSPProducAnalysisAgeBand15000Female65To74Textbox("ProductAnalysis_AgeProfile_BsspAgeBandRows_0__Agebands_2__FemaleCount", "BSSPProducAnalysisAgeBand15000Female65To74"),
    QuotesBSSPProducAnalysisAgeBand15000Male75To84Textbox("ProductAnalysis_AgeProfile_BsspAgeBandRows_0__Agebands_3__MaleCount", "BSSPProducAnalysisAgeBand15000Male75To84"),
    QuotesBSSPProducAnalysisAgeBand15000Female75To84Textbox("ProductAnalysis_AgeProfile_BsspAgeBandRows_0__Agebands_3__FemaleCount", "BSSPProducAnalysisAgeBand15000Female75To84"),
    QuotesBSSPProducAnalysisAgeBand15000Male85To100Textbox("ProductAnalysis_AgeProfile_BsspAgeBandRows_0__Agebands_4__MaleCount", "BSSPProducAnalysisAgeBand15000Male85To100"),
    QuotesBSSPProducAnalysisAgeBand15000Female85To100Textbox("ProductAnalysis_AgeProfile_BsspAgeBandRows_0__Agebands_4__FemaleCount", "BSSPProducAnalysisAgeBand15000Female85To100"),
    QuotesSaveProfileButton("//input[@type='submit' and @value='Save Profile']", "Save Profile"),
    QuotesProducAgeProfileButton("//input[@type='submit' and @value='Produce Age Profile >>']", "Produc Age Profile"),
    QuotesPreviousButton("//input[@type='submit' and @value='<< Previous']", "Previous"),
    QuotesLeftNavHeader("lNavHeader", "lNavHeader"),    
    QuotesMinReqFieldset("//fieldset[@class='fieldsetSection']//table//tbody", "Quote Minimum Requirements Fields"),
    QuotesApproveLink("AcceptDecline", "Quotes Approve"),
    QuotesAcceptRadioButton("//input[@class='accept' and @id='ApproveDecision_ApproveDecisionDescription']", "Quotes Accept"),
    QuotesDeclineRadioButton("//input[@class='decline' and @id='ApproveDecision_ApproveDecisionDescription']", "Quotes Decline"),
    QuotesSaveAndCloseButton("declineAccept", "Save and Close"),
    QuotesProductOptionMethodDropDown("//div[@class='mainContent']//form[@class='ageanalysis']//div[@id='ageprofilecontainer']//div//fieldset//div//span//select[@id='MethodId']", "Age Analysis Product Method"),
    QuotesAddProductOptionButton("//div[@class='mainContent']//form[@class='ageanalysis']//div[@id='ageprofilecontainer']//div//fieldset//div//span//span//input[@value='Add Product Option']", "Age Analysis Add Product Option"),
    QuotesAddNewQuoteProductOptionButton("//div[@class='mainContent']//form[@class='ageanalysis']//div[@id='ageprofilecontainer']//div//fieldset//div//span//span//input[@value='Add Product Option']", "Age Analysis Add Product Option"),
    QuotesProductDropDown("ddlProducts", "Quotes Product"),
    QuotesCoverDropDown("ddlCovers", "Quotes Cover"),
    QuotesAssesLink("Assess", "Quotes Assess"),
    QuotesSaveAndProduceAgeProfileButton("//div[@id='ui-tabs-3']//input[@type='submit' and @value='Save & Produce Age Profile']", "Quotes Save and Produce Age Profile"),
    QuotesConfirmAssessment("", "Quotes Save and Produce Age Profile"),
    SchemesCashBackIndicatorCheckBox("QuoteInformation_Scheme_CashbackIndicator", "Cash back Indicator"),
    /*
     * Cancel Page
    */
    SchemesCancelLink("Cancel", "Cancel Scheme Link"),    
    SchemeCancelSchemeReasonTable("//div[@id='ui-tabs-6']//div[@id='schemeCancelWrapper']//form[@action='/OneFM/Scheme/CancelScheme']//table//tbody", "Cancel Scheme Reason Table"),    
    SchemeCancelSchemeButton(SchemeCancelSchemeReasonTable.elementId + "//input[@id='id' and @type='submit' and @value='Cancel Scheme']", "Cancel Scheme Button"),
    ;
    private final String elementId;
    private final String elementNameOnPage;

    PageElements(String elementId, String elementNameOnPage) {
        this.elementId = elementId;
        this.elementNameOnPage = elementNameOnPage;
    }

    public String getElementId() {
        return elementId;
    }
    
    public String getElementNameOnPage() {
        return elementNameOnPage;
    }
}
